[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "ruby", "python"]

[settings.aqua]
github_attestations = false

[tools]
python = "3.13.0"
ruby = "4.0.1"

"npm:oxlint" = "latest"
"npm:prettier" = "latest"
gh = "latest"
glab = "latest"
node = "24.12.0"
pnpm = "latest"
yarn = "4.12.0"

